# Generated by Django 5.2.4 on 2025-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medicine', max_length=255)),
                ('batch_number', models.CharField(help_text='Unique batch number', max_length=100, unique=True)),
                ('manufacturing_date', models.DateField(help_text='Manufacturing date')),
                ('expiry_date', models.DateField(help_text='Expiry date')),
                ('manufacturer', models.CharField(help_text='Manufacturer name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['-created_at'],
            },
        ),
    ]
