# Generated by Django 5.1.7 on 2025-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='caution',
            field=models.TextField(blank=True, help_text='Cautionary information', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, help_text='Medicine description', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price', max_digits=10, null=True),
        ),
    ]
